version: '3.8'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server1
    container_name: server1
    ports:
      - "8081:8081"

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server2
    container_name: server2
    ports:
      - "8082:8082"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2